# Generated by Django 2.2.4 on 2019-09-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20190905_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-created']},
        ),
    ]
